---
title: "Housing"
output: html_document
date: "2025-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Housing

```{r}
library(ggplot2)
library(ggdist)
library(dplyr)
library(glue)
library(scales)
library(ggtext)
```

```{r}
data_compra <- read.csv("data/spanish_houses_compra.csv")
```


```{r}
data_compra$price <- as.numeric(data_compra$price)

# Top provincias
top_provincias <- data_compra %>%
  count(prov, sort = TRUE) %>%
  slice_head(n = 21) %>%
  pull(prov)

# Filtrar: solo provincias seleccionadas + precios menores a 1 millón
df_plot <- data_compra %>%
  filter(prov %in% top_provincias, price < 1e6)  # equivalente a 1000000

# Mediana global
median_price <- median(df_plot$price, na.rm = TRUE)

# Plot
ggplot(df_plot, aes(x = forcats::fct_reorder(prov, price, .fun = median), y = price)) +
  stat_halfeye(
    aes(fill = stat(level)),
    adjust = 1,
    .width = c(.5, .8, .95),
    justification = 0,
    point_colour = NA,
    alpha = 0.3
  ) +
  stat_summary(
    geom = "point",
    fun = median,
    shape = 21,
    size = 2,
    fill = "black",
    color = "black",
    stroke = 0.3
  ) +
  geom_hline(yintercept = median_price, linetype = "dashed", color = "red") +
  coord_flip(ylim = c(0, 1000000), clip = "off") +
  scale_fill_manual(
    values = c("#c6dbef", "#9ecae1", "#6baed6"),
    guide = "none"
  ) +
  scale_y_continuous(
    labels = comma,
    breaks = seq(0, 1000000, by = 100000)
  ) +
  labs(
    x = NULL,
    y = "Precio en euros"
  ) +
  theme_minimal(base_family = "sans") +
  theme(
    plot.background = element_rect(fill = "grey97", color = NA),
    panel.grid = element_blank(),
    panel.grid.major.x = element_line(linewidth = 0.1, color = "grey75"),
    axis.text.y = element_text(hjust = 0, margin = margin(r = -5), face = "bold", size = 10),
    axis.text.x = element_text(size = 8),
    plot.margin = margin(10, 30, 10, 10),
    axis.title.y = element_text(margin = margin(r = 10))
  )

ggsave("grafico.png", width = 12, height = 10, dpi = 300)
```
